Properties:
  # When set to true, the hard-coded collisions created by ProjectKorra
  # and other addons will be removed.
  DisableCoreCollisions: true

  # What file the collisions will be loaded from. This allows you to
  # create multiple collision files to switch between.
  CollisionFile: "collisions.txt"

  # When true, the plugin will output all collisions registered
  Verbose: false
