name: CollisionUtility
author: KWilson272
main: me.kwilson272.collisionutility.CollisionUtility
version: 1.0.1
api-version: 1.16.5
description: ProjectKorra addon plugin to more easily customize collisions
depend: [ProjectKorra]