package me.kwilson272.collisionutility.parser.token;

/**
 * Record class to represent a complete token generated by the lexer.
 * @param type the TokenType defining this object
 * @param literal the String this token represents
 * @param lineNumber the Line number this token was derived from
 */
public record Token(TokenType type, String literal, int lineNumber) {}
